; PlatformIO Project Configuration File
; EnvMon ESP32-S3-N16R8 固件 v8.0.0

[platformio]
default_envs = esp32
src_dir = esp32

[env:esp32]
platform = espressif32 @ ~6.7.0
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter = +<*>
board_build.partitions = huge_app.csv
board_build.f_cpu = 240000000L
board_build.flash_mode = dio
board_build.flash_size = 16MB
monitor_speed = 115200
upload_speed = 921600
build_flags = 
	-DCORE_DEBUG_LEVEL=1
	-DARDUINO_ARCH_ESP32
	-DFIRMWARE_PLATFORM="esp32"
	-DPIN_OLED_SDA=8
	-DPIN_OLED_SCL=9
	-DPIN_DHT=4
	-DPIN_MIC_SD=-1
	-DPIN_MIC_SCK=-1
	-DPIN_MIC_WS=-1
	-DPIN_SPK_DOUT=38
	-DPIN_SPK_BCLK=18
	-DPIN_SPK_LRC=39
	-DPIN_ECG_OUT=-1
	-DPIN_ECG_REF=-1
	-DPIN_LED=2
	-DPLATFORM_SERVER="172.22.22.83"
	-DPLATFORM_PORT=12090
	-DDEVICE_ID="esp32-001"
	-DDEVICE_TOKEN=""
	-DREPORT_INTERVAL=60
lib_extra_dirs = lib
lib_deps = 
	adafruit/Adafruit SSD1306@^2.5.7
	adafruit/Adafruit GFX Library@^1.11.6
	adafruit/Adafruit BMP280 Library@^2.5.1
	adafruit/DHT sensor library@^1.4.6
	bblanchon/ArduinoJson@^6.21.1
